### ISSUE TITLE
输出整页对横竖混合文档支持不善

### ISSUE THREAD

**Issue by ivysrono** [wangsijie/pdf2jpg#5]
[vertical-horizontal.pdf](https://github.com/wangsijie/pdf2jpg/files/6467244/vertical-horizontal.pdf)
![vertical-horizontal](https://user-images.githubusercontent.com/2649544/118002099-e20f4b80-b379-11eb-95a4-68019476b8ca.jpg)

还没有详细测试一页一页输出能否自动识别页面方向。

**Comment by wangsijie** [comment]
之前没有考虑这种情况，问题确认存在
